const { createApp } = Vue;

createApp({
  data () {
    return {
      firstName: '',
      lastName: '',
      streetAddress: '',
      city: '',
      state: 'MN',
      availableStates: [
        { value: 'AL', usa: 'Alabama' },
        { value: 'AK', usa: 'Alaska' },
        { value: 'AZ', usa: 'Arizona' },
        { value: 'AR', usa: 'Arkansas' },
        { value: 'CA', usa: 'California' },
        { value: 'CO', usa: 'Colorado' },
        { value: 'CT', usa: 'Connecticut' },
        { value: 'DE', usa: 'Delaware' },
        { value: 'FL', usa: 'Florida' },
        { value: 'GA', usa: 'Georgia' },
        { value: 'HI', usa: 'Hawaii' },
        { value: 'ID', usa: 'Idaho' },
        { value: 'IL', usa: 'Illinois' },
        { value: 'IN', usa: 'Indiana' },
        { value: 'IA', usa: 'Iowa' },
        { value: 'KS', usa: 'Kansas' },
        { value: 'KY', usa: 'Kentucky' },
        { value: 'LA', usa: 'Louisiana' },
        { value: 'ME', usa: 'Maine' },
        { value: 'MD', usa: 'Maryland' },
        { value: 'MA', usa: 'Massachusetts' },
        { value: 'MI', usa: 'Michigan' },
        { value: 'MN', usa: 'Minnesota' },
        { value: 'MS', usa: 'Mississippi' },
        { value: 'MO', usa: 'Missouri' },
        { value: 'MT', usa: 'Montana' },
        { value: 'NE', usa: 'Nebraska' },
        { value: 'NV', usa: 'Nevada' },
        { value: 'NH', usa: 'New Hampshire' },
        { value: 'NJ', usa: 'New Jersey' },
        { value: 'NM', usa: 'New Mexico' },
        { value: 'NY', usa: 'New York' },
        { value: 'NC', usa: 'North Carolina' },
        { value: 'ND', usa: 'North Dakota' },
        { value: 'OH', usa: 'Ohio' },
        { value: 'OK', usa: 'Oklahoma' },
        { value: 'OR', usa: 'Oregon' },
        { value: 'PA', usa: 'Pennsylvania' },
        { value: 'RI', usa: 'Rhode Island' },
        { value: 'SC', usa: 'South Carolina' },
        { value: 'SD', usa: 'South Dakota' },
        { value: 'TN', usa: 'Tennessee' },
        { value: 'TX', usa: 'Texas' },
        { value: 'UT', usa: 'Utah' },
        { value: 'VT', usa: 'Vermont' },
        { value: 'VA', usa: 'Virginia' },
        { value: 'WA', usa: 'Washington' },
        { value: 'WV', usa: 'West Virginia' },
        { value: 'WI', usa: 'Wisconsin' },
        { value: 'WY', usa: 'Wyoming ' }
      ],
      selectedColors: [],
      colors: [
        { name: 'White', value: 'white' },
        { name: 'Beige', value: 'beige' },
        { name: 'Fawn (light, medium, dark)', value: 'fawn' },
        { name: 'Brown (light, medium, dark)', value: 'brown' },
        { name: 'Bay Black', value: 'bay-black' },
        { name: 'True Black', value: 'true-black' },
        { name: 'Silver (light, medium, dark)', value: 'silver' },
        { name: 'Rose Grey (light, medium, dark)', value: 'rose-grey' }
      ],
      status: ''
    }
  }
}).mount('#alpacaForm');
